import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between bg-slate-200 px-2 py-4">
          <Link href="/" className="text-lg">
            Movie Website
          </Link>
          <button className="text-lg">Search</button>
        </header>
        <main className="flex flex-col items-center gap-4 p-4">{children}</main>
      </body>
    </html>
  );
}
